name: Testcontainer

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Install Docker
        uses: actions/setup-docker@v3

      - name: Build project
        run: ./gradlew clean build

      - name: Run integration tests
        run: ./gradlew integrationTest
