name: Testcontainer

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build project
        run: mvn clean install -pl s3 -am

      - name: Run integration tests
        run: mvn integration-test -pl s3 -am
          mvn -Dtest=ch.oidc.testenv.ContainerEnvTest test
